<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EJ0N1V7" failures="1" tests="4" name="Test" time="17.668" errors="0" timestamp="2022-08-09T11:14:46 IST">
  <testcase classname="com.sauce.TestcaseClass.TC004_VerifyMultiproductFunctionality" name="verifyMultipleProductFunctionality" time="1.781">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.sauce.TestcaseClass.TC004_VerifyMultiproductFunctionality.verifyMultipleProductFunctionality(TC004_VerifyMultiproductFunctionality.java:35)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyMultipleProductFunctionality -->
  <testcase classname="com.sauce.TestcaseClass.TC002_VerifyLogOutFunctionality" name="logOutFunctionality" time="0.948"/>
  <testcase classname="com.sauce.TestcaseClass.TC003_VerifySingleProductAddtocartFunctinality" name="verfySingleBagFunctionality" time="0.44"/>
  <testcase classname="com.sauce.TestcaseClass.TC001_VerifyloginFunctionality" name="loginFunctionality" time="0.192"/>
</testsuite> <!-- Test -->
